/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    APITemplate: typeof import('./src/components/ConfirmDialog/APITemplate.vue')['default']
    CircleList: typeof import('./src/components/CircleList.vue')['default']
    ClipBoard: typeof import('./src/components/ClipBoard.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog/index.vue')['default']
    DialogContent: typeof import('./src/components/DialogContent.vue')['default']
    OtherLoading: typeof import('./src/components/OtherLoading/OtherLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Safe: typeof import('./src/components/OtherLoading/components/Safe.vue')['default']
    SubmitLoading: typeof import('./src/components/OtherLoading/SubmitLoading.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanPopup: typeof import('vant/es')['Popup']
    WxApplet: typeof import('./src/components/wxRelated/wxApplet.vue')['default']
    WxPublicAccountModal: typeof import('./src/components/wxRelated/wxPublicAccountModal.vue')['default']
    WxSubscribe: typeof import('./src/components/wxRelated/wxSubscribe.vue')['default']
    WxSubscribeModal: typeof import('./src/components/wxRelated/wxSubscribeModal.vue')['default']
  }
}
