import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from '@/app/providers/StoreProvider'
import 'antd-mobile/es/global'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics
}: Readonly<{
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 服务端组件部分 - 无Provider */}
        <header>
          <h1>应用标题 (服务端渲染)</h1>
        </header>
        <StoreProvider>
          {children}
          {team}
          {analytics}
        </StoreProvider>
        {/* 服务端组件部分 - 无Provider */}
        <footer>
          <p>页脚内容 (服务端渲染)</p>
        </footer>
      </body>
    </html>
  );
}
