import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {locales} from '@/config'
import styles from './index.module.scss'
import SideBar from './note/components/Sidebar'
import Header from './note/components/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <div className={styles.note}>
          <SideBar />
          <section className={styles.main}>{children}</section>
        </div>
      </body>
    </html>
  );
}
