import type { Metadata } from "next";
import "./globals.css";
import styles from './index.module.scss'
import SideBar from './note/components/Sidebar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body
      >
        <div className={styles.note}>
          <SideBar />
          <section className={styles.main}>{children}</section>
        </div>
      </body>
    </html>
  );
}
