import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd-mobile/es/global'
import {locales} from '@/config'
import styles from './index.module.scss'
import SideBar from './note/components/Sidebar'
import Footer from './note/components/Footer'
import Header from './note/components/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }))
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode,
  params: {
    lng: string;
  };
}>) {
  const {lng} = await params
  return (
    <html lang={lng}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <div className={styles.note}>
          <SideBar lng={lng} />
          <section className={styles.main}>{children}</section>
        </div>
        <Footer lng={lng} />
      </body>
    </html>
  );
}
